---
title: "Ebola_google_trends"
output:
  html_document:
    fig_caption: yes
    theme: spacelab
    toc: no
---

## Plotting ebola google trends observed and modelled using Fraxinus function

Load libraries and the data
```{r setup, include=FALSE}
library(knitr)
library(markdown)
opts_chunk$set(dev = 'pdf')
# load the required libraries and functions
library(ggplot2)
library(gridExtra)
library(reshape2)

mytheme <- theme(panel.background = element_rect(fill='white', colour='black'),
        text = element_text(size = 20, face='bold', colour='black'),
        axis.title.x = element_text(size = 19, face='bold', color='black', vjust = -1),
        axis.text = element_text(size = 17, face='bold', color='black'),
        panel.grid.major = element_line(linetype = 'dotted', colour='black'),
        panel.border = element_rect(fill=NA, linetype = "solid", colour='black'),
        plot.margin=unit(c(2,2,5,2),'mm'))

weekly_searches <- read.delim(file = "ebola_trends_weekly_searches.csv", sep = ",", header = T)
colnames(weekly_searches) <- c("week", "google_trends")
weekly_searches$days <- as.Date(as.character(gsub("^201[4,5]-[0-1][1-9]-[0-3][1-9] - ", "", weekly_searches$week)),'%Y-%m-%d')
start_d <- as.Date(as.character("2014-08-01"),'%Y-%m-%d')
end_d <- start_d + 240
select_trends <- subset(weekly_searches, days >= start_d & days <= end_d)
rownames(select_trends) <- NULL
select_trends$weeknum <- as.numeric(rownames(select_trends))

model_data <- read.delim(file="searches_ebola_model.txt", header = T)
select_trends$modelled <- ""
select_trends$modelled[1] <- 0
x = 2
i = 1
while(i <= nrow(model_data)){
  j = i + 6
  if (j <= nrow(model_data)){
    select_trends$modelled[x] <- round( mean(model_data$searches[i:j]) )
    x = 1 + x
  }
    i = 7 + i
}
select_trends$modelled <- as.numeric(select_trends$modelled)

```


### Supplemental figure
### Google trends of ebola search and modelled data

```{r FigureSnew, echo=FALSE, fig.width=12, fig.height=6.5}
molten_data <- melt(select_trends, id.vars=c("weeknum", "days", "week"), variable.name = "data_type")
cols <- c("google_trends"="#000000", "modelled"="orange")

ggplot(data=molten_data) + geom_point(aes(x=weeknum, y=value, colour=data_type)) + geom_line(aes(x=weeknum, y=value, colour=data_type), size=1) + labs(x="Week Number", y="Number of searches") + mytheme + 
  theme(legend.position=c(0.8,0.9), legend.key.height=unit(1, "cm"), legend.key.width=unit(1, "cm"), legend.title = element_blank(), legend.text = element_text(colour = 'black', size = 19, face = 'bold'), legend.direction='vertical', legend.box='horizontal') +
  scale_colour_manual(values = cols, breaks=c("google_trends", "modelled"),
                      labels=c("Google trends for ebola", "Modelled ebola trends data"))

```

...    	

### Sum of searches from Google trends of ebola weekly data

### `r sum(select_trends$google_trends)`


### Sum of searches from Modelled trends of ebola weekly data

### `r sum(select_trends$modelled)`

...			
